### ISSUE TITLE
UnKnown error com.yj.app.MainActivity@1242d02is not a puppet object

### ISSUE THREAD

**Issue by zouxianbincc** [JustKiddingBaby/FragmentRigger#13]
不知道作者是否遇到过下面的问题：com.jkb.fragment.rigger.exception.RiggerException: UnKnown error com.yj.app.MainActivity@1242d02is not a puppet object

环境是：android studio 3.0  com.android.tools.build:gradle:3.0.1
我没有修改您的任何代码。只是运行了一下您的工程， app 安装完成后，一打开，就出现上述错误

**Comment by zouxianbincc** [comment]
运行手机是系统是7.0的

**Comment by JustKiddingBaby** [comment]
@zouxianbincc 请关闭`Instant Run`。

**Comment by bandung88** [comment]
I got same error, and instant run is already turned off, also i have trying clean, rebuild, restarting program but still got same issue :(

**Comment by JustKiddingBaby** [comment]
@bandung88  
>you can fix this issue by wiki [Errors in gradle](https://github.com/JustKiddingBaby/FragmentRigger/wiki/Errors-in-gradle)

**If you find other errors that the wiki does not contained, please let me know ;)**
