### ISSUE TITLE
在fragment中如何重新加载数据

### ISSUE THREAD

**Issue by HappyImp** [JustKiddingBaby/FragmentRigger#14]
比如我想切换到此fragment后重新加载数据，该怎么处理呢

**Comment by JustKiddingBaby** [comment]
@HappyImp 可以在Fragment中重写`onHiddenChanged(boolean hidden)`方法并根据`hidden`判断Fragment是否为hide状态。

**Comment by HappyImp** [comment]
这方法我有试，但好像不是所有时刻都能触发

**Comment by JustKiddingBaby** [comment]
@HappyImp 请列举出场景，我会验证并进行修复。

**Comment by HappyImp** [comment]
好的，我看看，之前我是这样处理的。但当时遇到点问题

**Comment by HappyImp** [comment]
在viewpager中使用tab切换，viewpager设置了limit

**Comment by HappyImp** [comment]
假如viewpager中4个fragment
limit 4，那么我在做切换的时候，是不会调用onHiddenChanged方法的

**Comment by HappyImp** [comment]
我现在的需求是需要关闭viewpager的预加载，然后每次fragment显示的时候能请求数据

**Comment by JustKiddingBaby** [comment]
@HappyImp ViewPager中是不会调用`onHiddenChanged`方法的，你可以在Fragment中重写`setUserVisibleHint(boolean isVisibleToUser)`并根据`isVisibleToUser`判断Fragment是否显示。

**Comment by HappyImp** [comment]
@JustKiddingBaby 但是在viewpager中frag1有调用setUserVisibleHint，但在frag1的子frag2没有调用setUserVisibleHint

**Comment by JustKiddingBaby** [comment]
@HappyImp 你可以自己在你的frag1中的`setUserVisibleHint`方法中调用frag2的`setUserVisibleHint`
* 如果知道frag2的tag，则可以通过`Rigger#findFragmentByTag`方法返回的Fragment进行设置。

**Comment by HappyImp** [comment]
好，我目前的方法就是在frag1的setUserVisibleHint中加入
` if (isVisibleToUser) {
                Rigger.getRigger(this).showFragment
                        (Rigger.getRigger(frag2).getFragmentTAG());
              
            } else {
                Rigger.getRigger(this).hideFragment(frag2);
                
            }`

**Comment by JustKiddingBaby** [comment]
@HappyImp 
>**建议：** 不要保存Fragment对象，建议在Fragment初始化的时候保存Tag，然后对Tag进行操作。  
new完Fragment直接可以使用`Rigger#getFragmentTAG`哦。

**本框架支持在`内存重启`后Fragment和Activity重新创建对象之后依旧保留对应的Rigger成员。**

**Comment by HappyImp** [comment]
ok
