### ISSUE TITLE
RiggerException: UnKnow error ** is not a puppet object.

### ISSUE THREAD

**Issue by zhaoxiuyu** [JustKiddingBaby/FragmentRigger#18]
这是我Activity 代码 
![7 hf z e3v4 ri h 4 ud6](https://user-images.githubusercontent.com/16554580/35027387-5d5c7380-fb8b-11e7-82ba-6bf0852540ab.png)

是这行代码报的错误
![sl qsjse k70fo l2](https://user-images.githubusercontent.com/16554580/35027403-7589a48c-fb8b-11e7-98a4-8b08803d41a5.png)

Fragment继承的BaseFragment 里面有注解 @Puppet

出现如下错误:
![9ae 9z_iu2_ n5 k uur p](https://user-images.githubusercontent.com/16554580/35027337-20c6f2c4-fb8b-11e7-9ad0-7f965a74a7b8.png)

**Comment by JustKiddingBaby** [comment]
@zhaoxiuyu 请确认是否关闭`Instant Run`，如果关闭，请贴出**根目录和module**下的`gradle`配置。可能是`AspectJ`没有正常工作。

**Comment by zhaoxiuyu** [comment]
buildscript {
    dependencies {

        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'
        classpath 'org.aspectj:aspectjtools:1.8.13'
    }
}
allprojects {
    repositories {

        maven { url 'https://jitpack.io' }
    }
}


apply plugin: 'android-aspectjx'


compile 'com.justkiddingbaby:fragment-rigger:1.0.1'

就这些配置，都是按照文档配置的，太麻烦了，已经换方案了

**Comment by JustKiddingBaby** [comment]
@zhaoxiuyu 好的,good luck ;)
