### ISSUE TITLE
按照文档第一步安装的操作配置gradle后，sync报错

### ISSUE THREAD

**Issue by NARUTONBM** [JustKiddingBaby/FragmentRigger#19]
Error:FAILURE: Build failed with an exception.

* What went wrong:
Could not find matching constructor for: org.gradle.util.Clock()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by JustKiddingBaby** [comment]
你的gradle版本号是多少？请发出你项目的`gradle-wrapper.properties`和根目录下的`build.gradle`配置。
>gradle在3.*和4.*上有些区别，要支持java8的话也需要特殊处理一下。

**Comment by NARUTONBM** [comment]
gradle我是用本地的，版本是4.4.1；

以下是根目录build.gradle
buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'
        classpath 'org.aspectj:aspectjtools:1.8.13'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by NARUTONBM** [comment]
对了，我的java之前用homebrew更新软件的时候更新到9.0.4了

**Comment by JustKiddingBaby** [comment]
@NARUTONBM 允许的话，你可以尝试使用`gradle4.1`版本，并升级aspectj插件
```
//根目录下build.gradle
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.1'
```
>近期`AspectJ`插件有重大问题，我会尝试在以后的版本中替换`AOP`的支持方案并全面测试。

**Comment by NARUTONBM** [comment]
非常感谢，按照你的建议，取消本地gradle，改用4.1并升级aspedtjx后，编译顺利通过
