### ISSUE TITLE
能用了吗？

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [JustKiddingBaby/FragmentRigger#2]
为什么一直提示： Failed to resolve: com.justkiddingbaby:fragment-rigger:1.0.0。

**Comment by JustKiddingBaby** [comment]
可以使用了，请把你的项目根目录下和module的build.gradle配置发出来。

**Comment by AcgnCodeMonkey** [comment]
都是照着文档配置的
根：
buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        //aop插件
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.10'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
项目：
apply plugin: 'android-aspectjx'
//aop插件
//省略中间部分配置
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testCompile mainGroup.Junit
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation project(':BaseCore')
    /* fragment管理框架*/
//    compile 'com.justkiddingbaby:fragment-rigger:1.0.0'
}

**Comment by JustKiddingBaby** [comment]
@AcgnCodeMonkey 不好意思，忘记关联到JCenter中了，您可以先clone项目查看demo，等JCenter关联成功后第一时间通知您～

**Comment by AcgnCodeMonkey** [comment]
ok，持续关注

**Comment by JustKiddingBaby** [comment]
@AcgnCodeMonkey JCenter已关联成功，可以正常使用了～
