### ISSUE TITLE
Fragment is not added into rigger

### ISSUE THREAD

**Issue by liangjianqi** [JustKiddingBaby/FragmentRigger#22]
RuntimeException: Unable to start activity ComponentInfo{XXXActivity}: com.jkb.fragment.rigger.exception.RiggerException: UnKnown error XXXActivity@3c64c01 is not added into rigger. please check your config or contact author.

compileSdkVersion 26
support-v4:26.1.0

**Comment by liangjianqi** [comment]
[https://github.com/JustKiddingBaby/FragmentRigger/tree/gradle/4/java8](url)

**Comment by Marshall1115** [comment]
app下builde.gradle添加
apply plugin: 'android-aspectjx'
