### ISSUE TITLE
懒加载无效

### ISSUE THREAD

**Issue by JakeHao** [JustKiddingBaby/FragmentRigger#23]
在fragment中配置这两个 @LazyLoad @Puppet  和 
  public void onLazyLoadViewCreated(Bundle savedInstanceState) {

  }
但是在懒加载方法没执行。

**Comment by JustKiddingBaby** [comment]
@JakeHao 请参考demo使用，如有疑问，请发出相关代码

**Comment by JakeHao** [comment]
@LazyLoad 
@Puppet 
public class ShoppingCartFragment extends BaseFragment<ShoppingCartPresenter>
    implements ShoppingCartContract.View, OnRefreshLoadmoreListener {
  public static final String KEY_TYPE = "key_type";
  @BindView(R.id.mRefreshLayout) RefreshLayout mRefreshLayout;
  @BindView(R.id.mRecyclerView) RecyclerView mRecyclerView;
  private ShoppingCartAdapter mAdapter;
  private StatusLayoutManager mStatusLayoutManager;

  public static ShoppingCartFragment newInstance(String type) {
    ShoppingCartFragment fragment = new ShoppingCartFragment();
    Bundle bundle = new Bundle();
    bundle.putString(ShoppingCartFragment.KEY_TYPE, type);
    fragment.setArguments(bundle);
    return fragment;
  }

  @Override public void setupFragmentComponent(AppComponent appComponent) {
    DaggerShoppingCartComponent //如找不到该类,请编译一下项目
        .builder()
        .appComponent(appComponent)
        .shoppingCartModule(new ShoppingCartModule(this))
        .build()
        .inject(this);
  }

  @Override
  public View initView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    return inflater.inflate(R.layout.public_refresh_loadmore_recyclerview, container, false);
  }

  @Override public void initData(Bundle savedInstanceState) {
    String type = getArguments().getString(KEY_TYPE);
    mPresenter.setType(type);
    initRecyclerView();
    initStatusLayout();
    mRefreshLayout.setOnRefreshLoadmoreListener(this);
  }

  private void initRecyclerView() {
    VirtualLayoutManager layoutManager = new VirtualLayoutManager(getActivity());
    mRecyclerView.setLayoutManager(layoutManager);
    DelegateAdapter mDelegateAdapter = new DelegateAdapter(layoutManager, false);
    List<DelegateAdapter.Adapter> mAdapterList = new ArrayList<>();
    mAdapterList.add(mAdapter);
    mDelegateAdapter.setAdapters(mAdapterList);
    mRecyclerView.setAdapter(mDelegateAdapter);
  }

  public void onLazyLoadViewCreated(Bundle savedInstanceState) {
    //do something in here
    mStatusLayoutManager.showLoadingLayout();
    mPresenter.getShoppingCartProduct(true);
  }

}

就只在这个一个fragment上使用了注解，其他还需要配置什么吗

**Comment by JakeHao** [comment]
找到了问题了,注解@puppet需要，放在该activity重写onCreate()和Fragment重写onAttach()类中，才能绑定生命周期

**Comment by JustKiddingBaby** [comment]
@JakeHao Activty和Fragment的生命周期不用强制重写哦，不过很高兴你的问题得到了解决，要是有其他问题，请提新的issue.
