### ISSUE TITLE
编译通过  运行报错

### ISSUE THREAD

**Issue by rcj60560** [JustKiddingBaby/FragmentRigger#25]
Error:Execution failed for task ':app:transformClassesWithRetrolambdaForDebug'.
> Missing javaCompileTask for variant: debug/0 from output dir: G:\mydemo\Fragments\FragmentRigger\app\build\intermediates\transforms\retrolambda\debug\0

不知道哪里出了问题 @JustKiddingBaby

**Comment by JustKiddingBaby** [comment]
@rcj60560 应该是`gradle`和`retrolambd`版本的兼容问题，请升级`retrolambd`版本。

```gradle
classpath 'me.tatarka:gradle-retrolambda:3.7.0'
```

**Comment by rcj60560** [comment]
@JustKiddingBaby 阿里嘎多
