### ISSUE TITLE
失去生命周期很烦 这玩意好像没办法

### ISSUE THREAD

**Issue by omjooo** [JustKiddingBaby/FragmentRigger#27]
rt

**Comment by JustKiddingBaby** [comment]
失去生命周期是什么意思呢？请详细描述你所遇到的问题或者场景。

**Comment by omjooo** [comment]
你跳转一个新的fragment 下面的那个fragment 没有onpause和onstop这个过程 关闭当前的fragment 下面展示的那个fragment也没有onstart和onresum的过程

**Comment by omjooo** [comment]
没办法想Activity的那种生命周期 要求会不会有点无理=。=

**Comment by JustKiddingBaby** [comment]
展示Fragment的时候只是对下面的Fragment做`show/hide`操作，当然没有生命周期变化。

你要是想要判断Fragment是否隐藏等状态。
* 可以使用`onHiddenChanged(boolean hidden)`方法。
* 在`ViewPager`嵌套`Fragment`场景下，`onHiddenChanged(boolean hidden)`方法是不生效的，可以使用`setUserVisibleHint(boolean isVisibleToUser)`判断Fragment的显示状态。

**Comment by ysy950803** [comment]
> 没办法想Activity的那种生命周期 要求会不会有点无理=。=

可以参考谷歌官方插件LifeCycle。
