### ISSUE TITLE
show场景下的onBackPressed()未支持

### ISSUE THREAD

**Issue by jxfjack** [JustKiddingBaby/FragmentRigger#28]
添加一个fragment 按返回键 close了,但是再次添加Fragment后,再按返回键 ,activity就退出了.你们遇到过吗? 这里还有个问题 就是我若是加了多层的fragment,按一次fragment会吧所有的fragment全部移除,怎么做到一层层移除?

**Comment by JustKiddingBaby** [comment]
请给出添加`Fragment`的相关源码及请确认`onRiggerBackPressed()`是否是`public`的，如有异常，请给出相关异常信息。

**Comment by xiaoyan159** [comment]
通过showFragment加载的Fragment，无法拦截回退按钮，这个在设计回退拦截的时候是不是就只是处理通过startFragment加载进来的fragment

**Comment by JustKiddingBaby** [comment]
@xiaoyan159 是的，`show`场景下的`onBackPressed`暂未支持，这种情况因为没有栈的管理比较特殊，所以还未实现。

**Comment by jxfjack** [comment]
@JustKiddingBaby 我说一下环境先.
1. Mainactivity中有 四个标签 tabA, tabB tabC tabD 初始化的时候 Rigger先addFragment,用.showFragment(tag)显示每个tab页面; 
2. 在tabD的页面 我又做了一个startFragment的添加内嵌fragment,就如同您的demo中的例子;
3.在tabD页面多层startFragment以后, 按返回会清掉D页面所有的fragment, 包含tabD的根fragment;
4. 这时候我切换到tabA页面, 这时候显示A页面,我再按返回, 程序返回后台了;


这里我查看下了 有这样几个问题 @Puppet BaseFragment , 然后 每个子Fragment也有@Puppet 这样 子Fragment监听返回是没有效果, 

估计是BaseFragment截断了, 但是我再BaseFragment里面重写BackPress 里面再调用一个抽象方法,让子Fragment实现 好像子Fragment不会调用; 

有很多逻辑上的问题 没办法管理 看看怎么处理下..或者提供些接口 我们自己自定义处理; 

若是只在BaseFragment注释Puppet, D页面start就只能在根目录下切换,但是好像close的时候会返回上一个, 不知道是不是我做的对象重新new还是怎么回事..

**Comment by JustKiddingBaby** [comment]
@jxfjack 抱歉，近期因为工作问题没有来得及回复框架中的问题，近期会对框架进行进一步迭代。

以下说说你遇到的问题：
>`A/B/C/D`四个`Fragment`是通过`show`方式进行添加的，但是框架还没有为`show`方式下添加的`Fragment`添加`onBackPressed()`方法支持。

**Comment by JustKiddingBaby** [comment]
@jxfjack  近期已经对返回键的监听进行了完整的设计，支持了所有场景下的`Fragment`的返回键监听，并支持任意级别的拦截，demo中封装了你提供的场景。
>请升级版本到`v1.3.0`，详细使用请看 [wiki](https://github.com/JustKiddingBaby/FragmentRigger/wiki/onBackPressed%E6%8B%A6%E6%88%AA)

**Comment by JustKiddingBaby** [comment]
@xiaoyan159 近期已经对返回键的监听进行了完整的设计，支持了所有场景下的Fragment的返回键监听，并支持任意级别的拦截。
> 请升级版本到`v1.3.0`，详细使用请看 [wiki](https://github.com/JustKiddingBaby/FragmentRigger/wiki/onBackPressed%E6%8B%A6%E6%88%AA)
