### ISSUE TITLE
关于出栈后的fragment不走生命周期的问题

### ISSUE THREAD

**Issue by yuanjj5549** [JustKiddingBaby/FragmentRigger#29]
ActivityA 内 startFragment A并显示，点击fragment A内按钮，startfragment B和fragment A是同一个container,当closeFragment B时，fragmentA不走生命周期

**Comment by JustKiddingBaby** [comment]
@yuanjj5549 这是肯定的，本质只是对`Fragment`进行`show/hide`操作，`Fragment`的生命周期是和`Activity`息息相关的，无法做到单独控制，你可以重写`onHiddenChanged`方法去判断是否重新展示。

**Comment by yuanjj5549** [comment]
斯内克自有妙计。
