### ISSUE TITLE
如果一次要出栈多个, 怎么做?

### ISSUE THREAD

**Issue by 13456961183** [JustKiddingBaby/FragmentRigger#3]

**Comment by JustKiddingBaby** [comment]
>每个`Activity`或者`Fragment`自身都会维护一个栈，**目前没有多个`Fragment`同时出栈的支持**，可以通过`Rigger.getRigger(this).close()`对自己所持有的所有`Fragment`进行出栈操作并且关闭自身。

**同时出栈多个Fragment会在近期添加支持。**

**Comment by 13456961183** [comment]
@JustKiddingBaby  这种方式, 应该会造成每个fragment都要执行退场动画, 会不会比较乱...

**Comment by JustKiddingBaby** [comment]
@13456961183 不会，退场动画只会在状态为`show`的Fragment中进行执行，`hide`状态下的不执行退场动画。
