### ISSUE TITLE
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.util.Clock()

### ISSUE THREAD

**Issue by lovejhf** [JustKiddingBaby/FragmentRigger#30]
Gradle Version 4.4
Android Plugin Version 3.1.0
编译未通过

**Comment by nickyrabit** [comment]
same here too

**Comment by JustKiddingBaby** [comment]
@lovejhf @as0026 请贴出你的根目录和module下的`build.gradle`和`gradle-wrapper.properties`

**Comment by JustKiddingBaby** [comment]
@nickyrabit please show me your `project build.gradle` and `gradle-wrapper.properties`.

**Comment by as0026** [comment]
@JustKiddingBaby 
Gradle Version 4.4
Android Plugin Version 3.1.1
后面我更改了gradle为3.3，插件版本为2.3.2就可以了

**Comment by RoyXing** [comment]
it's ok to download[gradle4.x branch](https://github.com/JustKiddingBaby/FragmentRigger/tree/gradle/4/java8)
then need to close instant run.
Gradle Version 4.1
Android Plugin Version 3.0.1

**Comment by ysy950803** [comment]
同样的方法，新项目用的最新的Studio全家桶，出现这个问题。
