### ISSUE TITLE
        java.lang.NoSuchMethodError: No static method aspectOf()

### ISSUE THREAD

**Issue by KomoriWu** [JustKiddingBaby/FragmentRigger#31]
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/jkb/fragment/rigger/aop/ActivityInjection; in class Lcom/jkb/fragment/rigger/aop/ActivityInjection; or its super classes (declaration of 'com.jkb.fragment.rigger.aop.ActivityInjection' appears in /data/app/com.helife.android.debug-1/base.apk:classes10.dex)

好不容易解决了插件编译的错误，现在加入功能时，就只是加了一个@Puppet  ，再次编译就出错了。。。

**Comment by JustKiddingBaby** [comment]
@KomoriWu 请贴出你的根目录和module下的`build.gradle`和`gradle-wrapper.properties`文件。
