### ISSUE TITLE
1.3.0 activity 返回键返回桌面时崩溃

### ISSUE THREAD

**Issue by HappyImp** [JustKiddingBaby/FragmentRigger#33]
大概就是 Exception in MessageQueue callback: handleReceiveCallback；
反射错误，应该是内部代码报错的。
没仔细研究，我换成1.0.1版本的无此问题

**Comment by JustKiddingBaby** [comment]
@HappyImp 请确认是否开启代码混淆并参考[代码混淆](https://github.com/JustKiddingBaby/FragmentRigger/wiki/ProGuard)

>Rigger已经升级到`1.4.0`
* 为`Activity/Fragment`添加滑动退出支持
