### ISSUE TITLE
onRiggerBackPressed() 这个方法不回调,不太清楚哪里出了问题?onInterruptBackPressed() 这个没有问题

### ISSUE THREAD

**Issue by miaowyg** [JustKiddingBaby/FragmentRigger#36]
如上,该怎么配置才可以使onRiggerBackPressed()  该方法得到回调?先谢谢了

**Comment by miaowyg** [comment]
直接回调了onKeyDown,现在可用...

**Comment by JustKiddingBaby** [comment]
@miaowyg  具体可以参考下 [LazyLoadFragment.java](https://github.com/JustKiddingBaby/FragmentRigger/blob/master/app/src/main/java/com/yj/app/test/lazyload/LazyLoadFragment.java) 和 [LoadContainerFragment.java](https://github.com/JustKiddingBaby/FragmentRigger/blob/master/app/src/main/java/com/yj/app/test/lazyload/LoadContainerFragment.java) 中的事件拦截处理。
