### ISSUE TITLE
Could not find matching constructor for: org.gradle.util.Clock()

### ISSUE THREAD

**Issue by mradzinski** [JustKiddingBaby/FragmentRigger#37]
Gradle tools version: 3.1.3
Android Studio version: 3.1.3
FragmentRigger version: 1.3.0

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not find matching constructor for: org.gradle.util.Clock()
```

**Comment by JustKiddingBaby** [comment]
@mradzinski  
>sorry for so late, please retry below config.

```
 // project gradle
 classpath 'com.android.tools.build:gradle:3.1.3'
 classpath 'org.aspectj:aspectjtools:1.8.13'
 classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.1'
```
>and the Rigger is updated to `v1.4.0`

* Add swipe back to exit Activity/Fragment

**Comment by JustKiddingBaby** [comment]
There is a same [issue](https://github.com/JustKiddingBaby/FragmentRigger/issues/39), this issue will be closed.
