### ISSUE TITLE
Could not find matching constructor for: org.gradle.util.Clock()

### ISSUE THREAD

**Issue by vijaykishan312** [JustKiddingBaby/FragmentRigger#39]
on gredle build  apply plugin: 'android-aspectjx'

any soluation so plz send my mail id
vijaykishan312@gmail.com

**Comment by francescosalamone** [comment]
same problem here

**Comment by JustKiddingBaby** [comment]
@vijaykishan312 @francescosalamone  please show me your `build.gradle` in your module and project.
