### ISSUE TITLE
studio3.0兼容性的问题

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [JustKiddingBaby/FragmentRigger#4]
studio3.0引入后编译通不过，百度了好久，也没找到解决方案，我看作者用的版本貌似不是3.0
错误信息：Execution failed for task ':Company:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder 'F:\workplace\SpeedLogistics\Company\build\intermediates\transforms\AspectTransform\debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

**Comment by JustKiddingBaby** [comment]
@AcgnCodeMonkey 因为我是在AS2.3上进行开发的，所以没有测试3.0的兼容性问题，我会在周末进行修复，修复完成会在第一时间告诉你～

**Comment by AcgnCodeMonkey** [comment]
找到个解决方法，你可以参考下，http://blog.csdn.net/fengrui_sd/article/details/78658103
插件升级后，编译终于通过了'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'

**Comment by iRYO400** [comment]
@AcgnCodeMonkey hey!
Same here. 
Updated as you said
`'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'`
But it doesn't help, maybe there is smthing else

**Comment by iRYO400** [comment]
Changed version to 1.1.1
`'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.1'`
And now it prints next in compile:
```
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.
> org/aspectj/bridge/MessageHandler
```

**Comment by JustKiddingBaby** [comment]
@iRYO400 you can try use `'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.1'` and close the `Instant Run`.
>my library is powered by [gradle_plugin_android_aspectjx](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx) , there is same problem,[Android Studio 3.0 build failed #64](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/64)
