### ISSUE TITLE
Non Puppet fragments should be ignored 

### ISSUE THREAD

**Issue by iFanie** [JustKiddingBaby/FragmentRigger#44]
I have a custom FrameLayout view which serves as a container for a Google map fragment. The SupportMapFragment gets added to the FrameLayout which in turn is used all over my implementation.

The problem arises when **BackClick** is triggered on an Activity or Fragment containing my custom FrameLayout. Rigger tries to invoke the back callbacks on **non stacked fragments**, which includes the SupportMapFragment of my custom view. This fragment is without a tag, so it isn't found in the **mRiggerTransaction** object and thus, a **_NotExistException_** is thrown.

The problem lies in _**_Rigger.java**_, on the **_dispatchBackPressed_** function. If a tag in the **_fragmentsWithoutStack_** array is null, it should be ignored. Or going back a step, when the **_fragmentsWithoutStack_** array is populated, in the _**getFragmentsWithoutStack**_ of the **_FragmentStackManager.java_** it should not include tags that are **null** or tags that don't belong in **_Puppet_** fragments.

**Comment by JustKiddingBaby** [comment]
@iFanie  the `tag` added into `FragmentStackManager` should never be null , it only add the `Fragment` with `@Puppet` annotation,  please show me the code to help me understand your problem.

**Comment by iFanie** [comment]
I have the following custom FrameLayout in the xml layout of my MapFragment. MapFragment is annotated with Puppet. The FrameLayout adds a GoogleMap fragment in itself, which obviously is not annotated with Puppet. Yet, I can see SupportMapFragment included in the FragmentStackManager its tag is null.

```kotlin
class GoogleMapView(context: Context, attributeSet: AttributeSet) : FrameLayout(context, attributeSet) {

    private var mapSubject: BehaviorSubject<GoogleMap>? = null

    init {
        if (!isInEditMode) {
            val mapFragment = SupportMapFragment.newInstance()
            val fragmentTransaction = (context as BaseActivity).supportFragmentManager.beginTransaction()

            fragmentTransaction.add(id, mapFragment)
            fragmentTransaction.commit()

            mapSubject = BehaviorSubject.create<GoogleMap>()

            Observable.create<GoogleMap> { emitter ->
                mapFragment.getMapAsync { map ->
                    emitter.onNext(map)
                }
            }.subscribe(mapSubject ?: throw RuntimeException("Uninitialized Google map"))
        } 
    }

}
```

**Comment by JustKiddingBaby** [comment]
@iFanie It's weird, i will test on weekend and solve the problem ASAP, please tell me the version of `Rigger` lib.

**Comment by iFanie** [comment]
@JustKiddingBaby, im using the latest version, 1.4.0
Thanks a lot, let me know if i can help you somehow.

**Comment by iFanie** [comment]
<img width="1440" alt="screen shot 2018-08-13 at 14 14 48" src="https://user-images.githubusercontent.com/33394385/44028755-a0b373f6-9f03-11e8-8707-885635dfbfa1.png">

**mFm** has the fragment with a null tag, neither **mFragmentContainerMap** nor **mFragmentStack** have the map fragment. So, i guess, a null check on line 192 would be sufficient.

**Comment by JustKiddingBaby** [comment]
@iFanie sorry for late, please update `Rigger` lib to `1.4.2` and try again.

**Comment by iFanie** [comment]
@JustKiddingBaby it has been fixed, thank you
