### ISSUE TITLE
求解，replaceFragment之后不加入栈的写法

### ISSUE THREAD

**Issue by sunlimiter** [JustKiddingBaby/FragmentRigger#45]
The fragment added by this method is not pushed in the stack，replace之后为什么用的add不是用的push
![image](https://user-images.githubusercontent.com/4102545/43935481-c926f148-9c86-11e8-8314-40a5ad0b5fda.png)

**Comment by JustKiddingBaby** [comment]
@sunlimiter `replace` 适用的场景：同一个`container`中只用于显示一个`Fragment`，所以`replace`方法内部会`add`新的`Fragment`并且`remove`掉所有在该`container`中的其他`Fragment`，从而保证该`container`只存在一个`Fragment`。

>请问现在遇到的问题是？

**Comment by sunlimiter** [comment]
@JustKiddingBaby 添加了一个新的Afragment，但是没有加入栈mFragmentStack，从Afragment启动Bfragment，mStackManager里面只有一个，然后调用close 关闭的时候remove之后，mStackManager.getFragmentStack().empty() 这里判断为空，就全部关闭了
或者是不是我哪里写错了...
![image](https://user-images.githubusercontent.com/4102545/43944099-5afab98c-9cb0-11e8-80af-c188a01dc87c.png)
