### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Can't change container ID of fragment DeviceListFragment{add691 id=0x7f090046 DeviceListFragment__dd4118ec}: was 2131296326 now 2131296455

### ISSUE THREAD

**Issue by WUSIR-ShiYan** [JustKiddingBaby/FragmentRigger#56]
我在代码中的使用：
@Override
protected void init(Bundle savedInstanceState) {
        DeviceListFragment devices = DeviceListFragment.newInstance();
        Rigger.getRigger(this).addFragment(R.id.container_devices, devices);
        Rigger.getRigger(this).showFragment(Rigger.getRigger(devices).getFragmentTAG());
        
        Rigger.getRigger(this.getActivity()).addFragment(R.id.main, devices);
}
我是想把这个fragment 也放到MainActivity的Rigger里面。
最底下那行报错，报错见标题，是我的用法不对吗？

**Comment by JustKiddingBaby** [comment]
```
@override
Rigger.getRigger(this).addFragment(R.id.container_devices, devices);
Rigger.getRigger(this.getActivity()).addFragment(R.id.main, devices);
```
devices 添加了两次，另外 Fragment 的操纵建议保存 tag ，并作出数据的保存。具体可以参考 [ShowFragment](https://github.com/JustKiddingBaby/FragmentRigger/blob/master/app/src/main/java/com/yj/app/test/show/ShowFragment.java) 中 `init` 方法和对于 `savedInstanceState` 的处理
