### ISSUE TITLE
在fragment嵌套fragment中报错了，错误如下;

### ISSUE THREAD

**Issue by huanyuan** [JustKiddingBaby/FragmentRigger#57]
Puppet Annotation class can only used on android.app.Activity or android.support.v4.app.Fragment

**Comment by JustKiddingBaby** [comment]
@huanyuan 请贴出关键代码，Rigger.getRigger() 中只能传入 `Fragment/Activity` 对象，请检查代码

**Comment by huanyuan** [comment]
在fragment嵌套fragment里边是viewpage，不知该怎么使用FragmentRigger啊，
 viewpager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i1) {
            }
            @Override
            public void onPageSelected(int position) {
                Rigger.getRigger(this).showFragment(mFragments.get(position), R.id.main_content_f);//这个容器用的是父类activity的，但现在这个fragment里没有了在，只有viewpager
            }
            @Override
            public void onPageScrollStateChanged(int i) {
            }
        });

例子里没有对应的fragment嵌套fragment的啊

**Comment by JustKiddingBaby** [comment]
@huanyuan  回调方法中的 `this` 指的是你的内部类对象。
