### ISSUE TITLE
Error compile/Implementation.

### ISSUE THREAD

**Issue by Devspm** [JustKiddingBaby/FragmentRigger#59]
Hi,
After installing the library dependency, there comes a error saying 

> Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. 

even though there is no compile keyword in my build file.

**Comment by JustKiddingBaby** [comment]
@Devspm please use `implementation` or `api` replace `compile`

**Comment by Devspm** [comment]
I already did, my project gradle doesn't contain a `Compile` keyword , I think the problems from the Library.

**Comment by JustKiddingBaby** [comment]
@Devspm i don't understand , what do you mean `my project gradle doesn't contain a compile keyword` ? can you show me the screenshot about it ?

**Comment by Devspm** [comment]
What i meant was  ,this problem started showing up after  i added fragment rigger library to my project for the first time, and it comes after after every time i rebuild the project. I have  checked the dependencies that i added , I can say i use `implementation`  for all the dependencies .

**Comment by JustKiddingBaby** [comment]
@Devspm please update `aspectJx` in your root `build.gradle` 

```
'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.1'
```
