### ISSUE TITLE
华为荣耀 KNT AL20机型一个诡异的异常，日志如下。

### ISSUE THREAD

**Issue by darkSuperman** [JustKiddingBaby/FragmentRigger#71]
1 android.view.ViewGroup.addViewInner(ViewGroup.java:4976)
2 android.view.ViewGroup.addView(ViewGroup.java:4807)
3 android.view.ViewGroup.addView(ViewGroup.java:4747)
4 android.view.ViewGroup.addView(ViewGroup.java:4720)
5 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
6 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
7 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
8 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
9 android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
10 android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2276)
11 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
12 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
13 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
14 android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:855)
15 android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2587)
16 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
17 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
18 android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
19 android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:781)
20 android.support.v4.app.FragmentationMagician$4.run(FragmentationMagician.java:134)
21 android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:194)
22 android.support.v4.app.FragmentationMagician.executePendingTransactionsAllowingStateLoss(FragmentationMagician.java:131)
23 me.yokeyword.fragmentation.TransactionDelegate$6.run(TransactionDelegate.java:172)
24 me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
25 me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
26 me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
27 me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)

**Comment by darkSuperman** [comment]
The specified child already has a parent. You must call removeView() on the child's parent first.

android.view.ViewGroup.addViewInner(ViewGroup.java:4976)

**Comment by JingYeoh** [comment]
看起来是 view 重复添加的异常，从异常信息中看不出来是框架导致的，麻烦打断点具体定位一下。
