### ISSUE TITLE
Attribute value must be constant

### ISSUE THREAD

**Issue by liuhedev** [JustKiddingBaby/FragmentRigger#78]
![image](https://user-images.githubusercontent.com/19663285/59987314-e5599b00-966c-11e9-81ae-0263d3693482.png)

lib使用rigger，提示如上错误。
Attribute value must be constant

**Comment by liuhedev** [comment]
另外，我在lib中同时引入了butterknife，不排除是否是引入了这个的原因
去掉此引用后，依然存在此问题

**Comment by JingYeoh** [comment]
@liuhedev 注解中只能使用常量，你可以使用 butterknife 中的 R2 进行资源引用
