### ISSUE TITLE
onRiggerBackPressed 不管用

### ISSUE THREAD

**Issue by jinzw1993** [JustKiddingBaby/FragmentRigger#8]
1.0.0 版本
在使用onRiggerBackPressed 拦截不到返回键。

**Comment by jinzw1993** [comment]
在Activity 可以拦截，但是fragment里面放置无效

**Comment by JustKiddingBaby** [comment]
@jinzw1993 请确认`onRiggerBackPressed `为`public`，该方法目前只在通过栈管理的Fragment中生效，即通过`startFragment`系列方法中的Fragment生效，在`show`和`replace`的场景下无效。

**Comment by jinzw1993** [comment]
谢谢大神，清楚了解了。希望大神有更完美的demo
