### ISSUE TITLE
编译报错 transformClassesWithDexBuilderForDebug

### ISSUE THREAD

**Issue by SageLu** [JustKiddingBaby/FragmentRigger#9]
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder 'D:\androidProjict\FragmentRigger-master\app\build\intermediates\transforms\AspectTransform\debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

添加了      multiDexEnabled true  ，还是不行
  defaultConfig {
       ..........
        multiDexEnabled true
    }

**Comment by JustKiddingBaby** [comment]
@SageLu 这属于`AsPectJ`依赖时候产生的错误，请把你根目录和`module`下的`gradle`配置发出来

**Comment by cuncunniu** [comment]
close your install run

**Comment by SageLu** [comment]
麻烦看一下~_~
@JustKiddingBaby 
> ## # **根目录gradle:**

`apply from: "config.gradle"

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        classpath 'com.novoda:bintray-release:0.5.0'

        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.10'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
        google()
    }
    tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

> ## **module 的gradle:**

`apply plugin: 'com.android.application'
apply plugin: 'android-aspectjx'

android {

    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId rootProject.ext.app.applicationId
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
        versionCode rootProject.ext.app.versionCode
        versionName rootProject.ext.app.versionName
        multiDexEnabled true
    }

    compileOptions {
        sourceCompatibility rootProject.ext.android.sourceCompatibilityVersion
        targetCompatibility rootProject.ext.android.targetCompatibilityVersion
    }

    signingConfigs {
        myConfig {
            storeFile file(rootProject.ext.store.storeKey)
            storePassword rootProject.ext.store.storePassword
            keyAlias rootProject.ext.store.keyAlias
            keyPassword rootProject.ext.store.keyPassword
            v2SigningEnabled false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            //是否清理无用资源
            shrinkResources false
            //是否启用zipAlign压缩
            zipAlignEnabled false
            signingConfig signingConfigs.myConfig
            versionNameSuffix rootProject.ext.app.versionNameSuffix
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.myConfig
            versionNameSuffix rootProject.ext.app.versionNameSuffix
        }
    }

    lintOptions {
        abortOnError false
    }
//    buildToolsVersion '26.0.2'
}


dependencies {
    compile rootProject.ext.dependencies.design
    compile project(':fragment-rigger')
    compile 'com.squareup.picasso:picasso:2.5.2'
}
`

**Comment by SageLu** [comment]
![default](https://user-images.githubusercontent.com/17927694/34399476-b1b6ad7a-ebc2-11e7-901a-1196c7b52e21.png)
@cuncunniu  unchecked ,but still useless?

**Comment by JustKiddingBaby** [comment]
@SageLu 请升级`AspectJ`的插件版本试试。
